### ISSUE TITLE
Broken CodeClimate badge

### ISSUE THREAD

**Issue by botandrose** [DatabaseCleaner/database_cleaner-redis#9]
@etagwerker Would you mind toggling CodeClimate on for this project?

**Comment by etagwerker** [comment]
@botandrose Sure, I just tried to do this but it seems that CodeClimate is down for me. 😢 

I'll try later today.

**Comment by etagwerker** [comment]
@botandrose Here it is: https://codeclimate.com/github/DatabaseCleaner/database_cleaner-redis/builds
